import prisma from '$lib/server/db';
import { v4 as uuidv4 } from 'uuid';

export class ActionQueueLog {
    decision_id: string;
    steps: { status: string; message: string; timestamp: string; description?: string }[] = [];

    constructor(decision_id: string) {
        this.decision_id = decision_id;
    }

    step(status: string, message: string, description?: string) {
        const timestamp = new Date().toISOString().replace('T', ' ').replace('Z', '');
        const statusIcon = status.includes('error') ? '🔴' : (status.includes('blocked') || status.includes('warning')) ? '🟡' : '🔵';
        console.log(`${statusIcon} [${timestamp}] Section 4 - ${status.toUpperCase()} : ${message}`);
        if (description) {
            console.log(`      → ${description}`);
        }
        this.steps.push({ status, message, timestamp, description });
    }
}

export class ActionQueueEngine {
    static async processToQueue(decisionId: string) {
        const log = new ActionQueueLog(decisionId);
        log.step('started', `Processing Decision ${decisionId} to Action Queue`, "Initialization of the Parameter Resolution engine. We are taking the strategic decision and preparing the individual work orders.");

        // 1. Fetch Decision Data
        const decision = await prisma.orchestratorDecision.findUnique({
            where: { decision_id: decisionId },
            include: { 
                event: { include: { enrichments: true } },
                action_queue: true // To check for existing records
            }
        });

        if (!decision) {
            log.step('error', `Decision not found: ${decisionId}`);
            throw new Error(`Decision not found: ${decisionId}`);
        }

        // 2. Duplicate Prevention Check
        if (decision.action_queue.length > 0) {
            log.step('warning', `Action Queue records already exist for decision ${decisionId}. Skipping re-processing.`, "Guard triggered to prevent duplicate work orders for the same decision.");
            return { queueItems: decision.action_queue, log };
        }

        const businessId = decision.event.business_id;
        if (!businessId) {
            log.step('error', `Business ID missing from event: ${decision.event.id}`);
            throw new Error(`Business ID missing from event: ${decision.event.id}`);
        }

        // 3. Deduplicate Selected Actions (Safety Net)
        const selectedActionIds = [...new Set(decision.selected_action_ids as string[])];
        log.step('actions_received', `Received ${selectedActionIds.length} unique action(s) from Orchestrator`, `The dispatcher has taken the deduplicated list of tasks generated by the Brain.`);

        const queueItems = [];

        // 4. Resolve Actions and Blocked Audit Records
        const allActionIds = [...selectedActionIds];
        const blockedAuditIds = (decision.blocked_action_ids as any[]) || [];

        // Combine for a complete audit trace in the queue
        for (const actionId of allActionIds) {
            const actionMeta = await prisma.actionLibrary.findUnique({ where: { action_id: actionId } });
            if (!actionMeta) {
                log.step('warning', `Action ${actionId} not found in library`);
                continue;
            }

            const lane = await this.determineLane(actionMeta, businessId, log);
            const requiredParams = (actionMeta.required_params as string[]) || [];
            const resolvedParams = await this.resolveParameters(requiredParams, decision, businessId, log);
            
            // Map Correct Status
            const status = lane === 'approval_required' ? 'pending_approval' : 'ready_for_execution';
            
            // Calculate SLA (12-hour window for approval tasks)
            const dueAt = lane === 'approval_required' ? new Date(Date.now() + 12 * 60 * 60 * 1000) : null;

            const qtraceId = `qtrace_${uuidv4().replace(/-/g, '').substring(0, 12)}`;

            const queueItem = await prisma.actionQueue.create({
                data: {
                    queue_trace_id: qtraceId,
                    decision_id: decision.id,
                    action_id: actionId,
                    execution_lane: lane,
                    parameters: resolvedParams,
                    status: status,
                    due_at: dueAt,
                    consultant_id: decision.consultant_id,
                    consultant_review_required: decision.consultant_review_required,
                    approval_route: decision.approval_route
                }
            });

            queueItems.push(queueItem);
            log.step('item_queued', `🎯 Queued: ${actionId} | Status: ${status.toUpperCase()} | Lane: [${lane.toUpperCase()}]`, `Action ${actionId} is successfully stored with trace ID ${qtraceId}.`);
        }

        // 5. Create Blocked Audit Records
        for (const blocked of blockedAuditIds) {
            const qtraceId = `qtrace_blocked_${uuidv4().replace(/-/g, '').substring(0, 8)}`;
            const blockedItem = await prisma.actionQueue.create({
                data: {
                    queue_trace_id: qtraceId,
                    decision_id: decision.id,
                    action_id: blocked.id,
                    execution_lane: 'blocked',
                    status: 'blocked_audit',
                    parameters: { block_reason: blocked.reason },
                    consultant_id: decision.consultant_id
                }
            });
            queueItems.push(blockedItem);
            log.step('blocked_audit', `Logged Blocked Action: ${blocked.id}`, `Preserved audit record for safety violation: ${blocked.reason}`);
        }

        log.step('completed', `Successfully processed ${queueItems.length} total queue/audit records`, "All strategic tasks have been turned into detailed work orders or blocked audit logs.");
        return { queueItems, log };
    }

    private static async determineLane(actionMeta: any, businessId: string, log: ActionQueueLog): Promise<string> {
        if (actionMeta.is_public_facing) {
            log.step('lane_assignment', `Action ${actionMeta.action_id} is public-facing. Forced to APPROVAL_REQUIRED per Safety Rule ORC-004.`, "Even if high automation was requested, the system has locked this public task into the Approval Lane for safety.");
            return 'approval_required';
        }

        const clientProfile = await prisma.clientOrchestratorProfile.findUnique({ where: { business_id: businessId } });
        if (clientProfile?.automation_level === 'aggressive') {
            log.step('lane_assignment', `Action ${actionMeta.action_id} set to AUTOMATIC via Aggressive automation profile.`, "This internal task will execute instantly based on the client's aggressive automation settings.");
            return 'automatic';
        }

        if (clientProfile?.automation_level === 'conservative') {
            log.step('lane_assignment', `Action ${actionMeta.action_id} set to APPROVAL_REQUIRED via Conservative automation profile.`, "The client's conservative profile requires a human check even for internal tasks.");
            return 'approval_required';
        }

        const lane = actionMeta.default_execution_mode || 'approval_required';
        log.step('lane_assignment', `Action ${actionMeta.action_id} using default lane: ${lane.toUpperCase()}`, `Applying the standard default lane for ${actionMeta.action_id}.`);
        return lane;
    }

    private static async resolveParameters(requiredParams: string[], decision: any, businessId: string, log: ActionQueueLog): Promise<Record<string, any>> {
        const params: Record<string, any> = {};
        const event = decision.event;
        const businessConfig = await prisma.businessConfiguration.findUnique({ where: { business_id: businessId } });
        const enrichment = event.enrichments?.[0] || {};

        for (const key of requiredParams) {
            switch (key) {
                case 'customer_name': params[key] = event.author_name || event.customer_profile?.display_name || 'Valued Customer'; break;
                case 'rating': params[key] = event.review_rating_numeric; break;
                case 'platform': params[key] = event.provider === 'google_business_profile' ? 'Google' : event.provider; break;
                case 'provider': params[key] = event.provider; break;
                case 'event_type': params[key] = event.event_type; break;
                case 'brand_tone': params[key] = businessConfig?.brand_tone || 'professional'; break;
                case 'office_hours': params[key] = businessConfig?.office_timezone || 'UTC'; break;
                case 'review_text': params[key] = event.review_text || event.unstructured_text; break;
                case 'text_content': params[key] = event.unstructured_text; break;
                case 'ai_summary': params[key] = enrichment.ai_summary; break;
                case 'sentiment': params[key] = enrichment.ai_sentiment; break;
                case 'intent': params[key] = enrichment.intent || enrichment.ai_requested_action || 'Unknown'; break;
                case 'phone_number': params[key] = event.customer_profile?.phone_number || 'Unknown'; break;
                case 'urgency_level': 
                    // Map deterministic priority to urgency level
                    if (decision.priority <= 1) params[key] = 'high';
                    else if (decision.priority === 2) params[key] = 'medium';
                    else params[key] = 'low';
                    break;
                case 'complaint_topics':
                    params[key] = enrichment.ai_complaint_topics || enrichment.complaint_topics || [];
                    break;
                default: params[key] = null;
            }
            log.step('param_resolved', `Resolved {${key}} -> ${params[key]}`, `Extracted the specific ${key} data point from the event context.`);
        }
        return params;
    }
}
